application: markbot-canvas-proxy
version: 1
runtime: php55
api_version: 1
threadsafe: yes

skip_files:
  - README.md
  - config.example.php
  - user-map.example.php
  - .gitignore
  - .editorconfig

handlers:
  - url: /grade.*
    script: grade.php
    secure: always
